### PR TITLE
alumni fix

### PR DESCRIPTION
**Pull request by Dicky1**

### CODE REVIEW

**Comment by restiyanada** [comment]
1. Highlight. 
image
2. Jenis Kelamin
image
3. typo
image
4. NIP ngga perlu bisa diedit.
image
5.  ilang sidebarnya?
image
6. dashboard ilangin aja.
image

**Comment by Dicky1** [comment]
silahkan di check kakak

**Review by restiyanada — COMMENTED** [review]
1. Jenis Kelamin
image
2. Highlight
image
3. NPPnya kok ilang?

**Comment by Dicky1** [comment]
NPP di database aja gak ada

**Comment by Dicky1** [comment]
sidebar susah kakak

**Pull request closed without merging**
